#' Advanced Table File Loader
#'
#' Allows customizing settings when loading table files (CSV, TSV, etc...) to
#' make it easier for users to use different file formats generated by various
#' programmes.
#'
#' @author Elias Hernandis

library(shiny)

# Module UI function
advancedTableFileLoaderInput <- function(id, label = 'Table loader') {
  # create a namespace to avoid name collisions with other modules / other instances of this one
  ns <- NS(id)

  tagList(
    actionLink(ns('modalLink'), label = label)
  )
}

# Module server function
advancedTableFileLoader <- function(input, output, session, id = 'namespace') {
  ns <- NS(id)

  inputModal <- function() {
    modalDialog(
      fluidPage(
        fluidRow(
          column(12,
                 fileInput(ns('inputFile'), 'File', width = '100%'))
        ),
        fluidRow(
          column(12,
                 helpText('Select file, then adjust parameters until the table preview looks right. Table should contain one marker per column and one allele per row.'))
        ),
        fluidRow(
          column(4,
                 radioButtons(ns('sep'), 'Column separator', choices = c(', (Comma)' = ',', '; (Semicolon)' = ';', '<TAB>' = '\t', '<SPACE>' = ' '))),
          column(4,
                 radioButtons(ns('quote'), 'Cell quoting', choices = c('None' = NULL, '" (Double quotes)' = '"', "' (Single quotes)" = "'"))),
          column(4,
                 p(strong('Headers')),
                 checkboxInput(ns('columnHeaders'), 'Column headers'),
                 checkboxInput(ns('rowHeaders'), 'Row headers'))
        ),
        fluidRow(
          column(4,
                 radioButtons(ns('dec'), 'Decimal separator', choices = c('. (Dot)' = '.', ', (Comma)' = ','))),
          column(4,
                 textInput(ns('na.strings'), 'NA strings', value = 'NA'),
                 helpText('String used in place of a value when none applies.')),
          column(4,
                 p(strong('Transpose')),
                 checkboxInput(ns('transpose'), 'Exchange rows and columns'))
        ),
        fluidRow(
          column(12,
                 tableOutput(ns('tablePreview'))),
          column(12,
                 helpText('Only first rows are shown in table preview.'))
        )
      ),
      title = 'Load a table file',
      footer = tagList(
        modalButton('Cancel'), # no id required as it always dismisses the modal
        actionButton(ns('ok'), 'OK')
      )
    )
  }

  # load file when one is chose or the options change
  dataframe <- reactive({
    # don't do anything until the user chooses a file
    req(input$inputFile)

    table = read.table(input$inputFile$datapath,
                       header = input$columnHeaders,
                       sep = input$sep,
                       quote = input$quote,
                       row.names = if (input$rowHeaders) 1 else NULL,
                       dec = input$dec,
                       na.strings = input$na.strings)

    if (input$transpose) t(table) else table
  })

  # display file preview
  output$tablePreview <- renderTable(head(dataframe()), rownames = TRUE, decimals = 4)

  # show modal when action link is clicked
  observeEvent(input$modalLink, {
    showModal(inputModal())
  })

  # dismiss modal when the user clicks OK
  observeEvent(input$ok, {
    removeModal()
  })

  return(dataframe)
}
